# 基础设置
debug = false
bind-to = "0.0.0.0:3128"  # MTG 实际监听端口
concurrency = 8192
prefer-ip = "prefer-ipv4"
domain-fronting-port = 443
tolerate-time-skewness = "5s"

# 网络设置
[network]
doh-ip = "9.9.9.9"
proxies = []

[network.timeout]
tcp = "5s"
http = "10s"
idle = "1m"

# 防御设置
[defense.anti-replay]
enabled = true
max-size = "1mib"
error-rate = 0.001

[defense.blocklist]
enabled = true
download-concurrency = 2
urls = ["https://iplists.firehol.org/files/firehol_level1.netset"]
update-each = "24h"

[defense.allowlist]
enabled = false

# 统计设置
[stats.statsd]
enabled = false

[stats.prometheus]
enabled = true
bind-to = "127.0.0.1:3129"
http-path = "/"
metric-prefix = "mtg"

# SSPanel 集成 (关键部分)
[sspanel]
enable = true
api-base-url = "https://your-sspanel-domain.com/api"  # SSPanel API 地址
node-id = "42"  # SSPanel 中配置的节点ID
api-key = "a1b2c3d4e5f6g7h8i9j0"  # SSPanel 中为此节点生成的API密钥
sync-interval = "10m"  # 用户列表同步间隔
heartbeat-interval = "2m"  # 心跳间隔
traffic-batch-size = 100  # 流量批量上报大小
traffic-flush-delay = "10s"  # 流量上报最大延迟